POST http://localhost/api/auth/sign-in
Content-Type: application/json

{
  "username": "farruxovic@gmail.com",
  "password": "112345sa_A"
}
###
POST http://localhost/api/auth/sign-up
Content-Type: application/json

{
  "username": "farruxovic@gmail.com",
  "password": "112345sa_A"
}
